# Generated by Django 5.1.3 on 2024-12-10 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
