# Generated by Django 5.1.3 on 2024-12-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_category_is_sub_category_slug_category_sub_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodcut',
            name='category',
        ),
        migrations.AddField(
            model_name='prodcut',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='products', to='web.category'),
        ),
    ]
