# Generated by Django 5.1.3 on 2024-12-14 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_prodcut_category_prodcut_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prodcut',
            new_name='Product',
        ),
    ]
