# Generated by Django 5.1.3 on 2024-12-22 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_product_recommended_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='recommended_products',
        ),
    ]
