# Generated by Django 5.1.3 on 2024-12-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_remove_product_recommended_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oder',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='oder',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='oder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='oder_iterm',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='sales',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
