# Generated by Django 5.1.3 on 2024-12-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
